# version: 2

# sphinx:
#   configuration: docs/source/conf.py

# python:
#   version: "3.8"
#   install:
#     - requirements: docs/source/requirements.txt


version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py

python:
  version: "3.8"
  install:
    - requirements: docs/source/requirements.txt